apiVersion: v1
kind: Secret
metadata:
  name: file-secret
type: Opaque
stringData:
  azurestorageaccountkey: "r+AIkn2qLv9HyOA09e7dyW+7OhEv5N20TETmX222zLP7HlYgMXJuj/W6QilgDoBsY8ySF/migEM9+AStvl5nHQ=="
  azurestorageaccountname: "elearnstate"